#!/bin/bash
#
# node-exporter       Start/Stop node_exporter
#
# chkconfig: 35 99 01
# description: node_exporter
#
# processname: node_exporter
#

# change this value as necessary
RUNAS=zookeeper
APP_DIR=/opt/zookeeper/node_exporter
APP_NAME=node_exporter

if [ -n "$RUNAS" ]; then
  # verify the specified run as user exists
  runas_uid="`id -u "$RUNAS"`"
  if [ $? -ne 0 ]; then
    echo "Utilisteur $RUNAS non trouvé !"
    exit 1
  fi
fi

start() {
    echo -n "Démarrage $APP_NAME"
    echo
    if [ -f $APP_DIR/$APP_NAME.pid ]; then
      echo "Fichier $APP_DIR/$APP_NAME.pid existe déjà !"
      exit 1
    else
      if [ -n "$RUNAS" ]; then
		su -c "$APP_DIR/$APP_NAME > /dev/null 2>&1 &" - "$RUNAS"
      else
        $APP_DIR/$APP_NAME > /dev/null 2>&1 &
      fi
      ps -ax |  grep "$APP_NAME" | grep -v "start" | grep -v "grep" | awk '{print $1}' > $APP_DIR/$APP_NAME.pid
    fi
}

stop() {
    echo -n $"Arrêt $APP_NAME"
    echo
    if [ -f $APP_DIR/$APP_NAME.pid ]; then
      kill -9 `cat $APP_DIR/$APP_NAME.pid`
      rm -f $APP_DIR/$APP_NAME.pid
    else
      echo "Fichier $APP_DIR/$APP_NAME.pid non trouvé !"
      exit 1
    fi
}

restart() {
    stop
    sleep 5
    start
}

case "$1" in
  start)
      start
    ;;
  stop)
      stop
    ;;
  restart)
      restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
exit $?
