apiVersion: v1
kind: Service
metadata:
  name: solrcloud
  labels:
    app: solr-app
spec:
  clusterIP: None
  selector:
    app: solr-app
---
apiVersion: v1
kind: Service
metadata:
  name: solr-service
  labels:
    app: solr-app
spec:
  ports:
  - name: client
    protocol: TCP
    port: 8983
    targetPort: 8983
  type: NodePort
  selector:
    app: solr-app
