apiVersion: v1
kind: PersistentVolume
metadata:
  name: solrcloud-vol1
spec:
  capacity:
    storage: 64Gi
  #volumeMode: Block
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: solrcloud-storage
  local:
    path: /k8s-storage/solrcloud-vol
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: target_solrcloud
          operator: In 
          values:
          - "yes"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: solrcloud-vol2
spec:
  capacity:
    storage: 64Gi
  #volumeMode: Block
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: solrcloud-storage
  local:
    path: /k8s-storage/solrcloud-vol
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: target_solrcloud
          operator: In 
          values:
          - "yes" 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: solrcloud-vol3
spec:
  capacity:
    storage: 64Gi
  #volumeMode: Block
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: solrcloud-storage
  local:
    path: /k8s-storage/solrcloud-vol
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: target_solrcloud
          operator: In 
          values:
          - "yes" 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: solrcloud-vol4
spec:
  capacity:
    storage: 64Gi
  #volumeMode: Block
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: solrcloud-storage
  local:
    path: /k8s-storage/solrcloud-vol
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: target_solrcloud
          operator: In 
          values:
          - "yes" 
