apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solrcloud
spec:
  selector:
    matchLabels:
      app: solr-app # has to match .spec.template.metadata.labels
  serviceName: solrcloud
  replicas: 2
  template:
    metadata:
      labels:
        app: solr-app # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: target_solrcloud
                operator: In 
                values:
                - "yes"       
      containers:
      - name: solr
        image: centos:8
        imagePullPolicy: IfNotPresent
        args:
        - "/bin/sh"
        - "-c"
        - "yum update -y && yum install -y which nmap sysstat iotop nmap-ncat net-tools bind-utils lsof wget git java-11-openjdk java-11-openjdk-devel && \
           cd /tmp && git clone https://github.com/bejean/solrcloud_kubernetes.git && cd solrcloud_kubernetes && git checkout dev_test && \
           chmod +x resources/solr/solr_install.sh && ./resources/solr/solr_install.sh && \
           /etc/init.d/solr start && /etc/init.d/node_exporter start && /etc/init.d/solr_exporter start && \
           tail -f /var/log/lastlog"
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 10
          httpGet:
            scheme: "HTTP"
            path: /solr/admin/info/health
            port: 8983
        readinessProbe:
          initialDelaySeconds: 300
          periodSeconds: 5
          httpGet:
            scheme: "HTTP"
            path: /solr/admin/info/system
            port: 8983
        volumeMounts:
        - name: solrcloud-vol-claim
          mountPath: /store
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SOLR_APP_DIR
            valueFrom:
              configMapKeyRef:
                name: solrcloud-config
                key: solrAppDir
          - name: SOLR_VERSION
            valueFrom:
              configMapKeyRef:
                name: solrcloud-config
                key: solrVersion
          - name: SOLR_DATA_DIR
            valueFrom:
              configMapKeyRef:
                name: solrcloud-config
                key: solrDataDir
          - name: ZOO_SERVERS
            valueFrom:
              configMapKeyRef:
                name: solrcloud-config
                key: zooServers
          - name: SOLR_XMX
            valueFrom:
              configMapKeyRef:
                name: solrcloud-config
                key: solrXmx
          - name: NODE_EXPORTER_VERSION
            valueFrom:
              configMapKeyRef:
                name: zkensemble-config
                key: nodeExporterVersion
          - name: JMX_EXPORTER_VERSION
            valueFrom:
              configMapKeyRef:
                name: zkensemble-config
                key: jmxExporterVersion
  volumeClaimTemplates:
  - metadata:
      name: solrcloud-vol-claim
    spec:
      storageClassName: solrcloud-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 60Gi
